// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var DateFns = require("date-fns");

var date1 = new Date();

var date2 = new Date();

var date3 = new Date();

var dates = /* array */[
  date2,
  date3
];

var closestIndexTo = DateFns.closestIndexTo(date1, dates);

console.log(closestIndexTo);

var closestTo = DateFns.closestTo(date1, dates);

console.log(closestTo);

var compareAsc = DateFns.compareAsc(date1, date2);

console.log(compareAsc);

var compareDesc = DateFns.compareDesc(date1, date2);

console.log(compareDesc);

exports.date1          = date1;
exports.date2          = date2;
exports.date3          = date3;
exports.dates          = dates;
exports.closestIndexTo = closestIndexTo;
exports.closestTo      = closestTo;
exports.compareAsc     = compareAsc;
exports.compareDesc    = compareDesc;
/* date1 Not a pure module */
