// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var DateFns    = require("date-fns");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var date1 = new Date();

var formattedDate = DateFns.format(date1, "DD/MM/YYYY");

var firstDate = new Date("01/01/2000");

var secondDate = new Date("01/02/2000");

var thirdDate = new Date("01/03/2000");

var fourthDate = new Date("01/04/2000");

var dates = /* array */[
  secondDate,
  thirdDate,
  fourthDate
];

var idx = DateFns.closestIndexTo(firstDate, dates);

console.log(Pervasives.string_of_int(idx));

var res = DateFns.closestTo(firstDate, dates);

console.log(DateFns.format(res, "DD/MM/YYYY"));

exports.date1         = date1;
exports.formattedDate = formattedDate;
exports.firstDate     = firstDate;
exports.secondDate    = secondDate;
exports.thirdDate     = thirdDate;
exports.fourthDate    = fourthDate;
exports.dates         = dates;
exports.idx           = idx;
exports.res           = res;
/* date1 Not a pure module */
