// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var DateFns    = require("date-fns");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var firstDate = new Date("01/01/2000");

var secondDate = new Date("01/02/2000");

var thirdDate = new Date("01/03/2000");

var fourthDate = new Date("01/04/2000");

var dates = /* array */[
  secondDate,
  thirdDate,
  fourthDate
];

var idx = DateFns.closestIndexTo(/* `Date */[
      758940238,
      firstDate
    ], /* `Dates */[
      -407535003,
      dates
    ]);

console.log(Pervasives.string_of_int(idx));

console.log(firstDate);

console.log(dates);

var res = DateFns.closestTo(firstDate, dates);

console.log(res);

console.log(DateFns.format(res, "DD/MM/YYYY"));

exports.firstDate  = firstDate;
exports.secondDate = secondDate;
exports.thirdDate  = thirdDate;
exports.fourthDate = fourthDate;
exports.dates      = dates;
exports.idx        = idx;
exports.res        = res;
/* firstDate Not a pure module */
